- name: Install GitLab dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - openssh-server
    - ca-certificates
    - postfix

- name: Add GitLab repository
  shell: "curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash"
  args:
    creates: /etc/apt/sources.list.d/gitlab_gitlab-ce.list

- name: Install GitLab CE
  apt:
    name: gitlab-ce
    state: present

- name: Configure GitLab
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb

- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure
