- name: Ensure PostgreSQL database and user are properly configured
  hosts: postgre_server
  become: true
  vars:
    postgres_password: "valeriesong"
    vagrant_password: "valeriesong"
  tasks:

    - name: Ensure PostgreSQL database 'prod' exists
      community.postgresql.postgresql_db:
        name: prod
        state: present
        login_user: postgres
        login_password: "{{ postgres_password }}"
        login_host: localhost
        port: 5432

    - name: Ensure PostgreSQL role 'vagrant' exists
      community.postgresql.postgresql_user:
        name: vagrant
        password: "{{ vagrant_password }}"
        role_attr_flags: LOGIN,CREATEDB
        login_user: postgres
        login_password: "{{ postgres_password }}"
        login_host: localhost
        port: 5432
        state: present

    - name: Grant privileges on database 'prod' to user 'vagrant'
      community.postgresql.postgresql_user:
        name: vagrant
        db: prod
        priv: ALL
        login_user: postgres
        login_password: "{{ postgres_password }}"
        login_host: localhost
        port: 5432
        state: present
